.PHONY: clean All

All:
	@echo "----------Building project:[ Solving_Problems - Release ]----------"
	@cd "/media/johk/Mainframe/cpp/Solving_Problems" && "$(MAKE)" -f  "Solving_Problems.mk"
clean:
	@echo "----------Cleaning project:[ Solving_Problems - Release ]----------"
	@cd "/media/johk/Mainframe/cpp/Solving_Problems" && "$(MAKE)" -f  "Solving_Problems.mk" clean
