.PHONY: clean All

All:
	@echo "----------Building project:[ jslam - Release ]----------"
	@cd "jslam" && "$(MAKE)" -f  "jslam.mk" PreBuild && "$(MAKE)" -f  "jslam.mk"
clean:
	@echo "----------Cleaning project:[ jslam - Release ]----------"
	@cd "jslam" && "$(MAKE)" -f  "jslam.mk" clean
